spring:
  application:
    name: user
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: false
  validate-on-migrate: true

grpc:
  server:
    port: 9091
    reflection-service-enabled: true

  client:
    character:
      address: static://localhost:9092
      negotiationType: plaintext
    item:
      address: static://localhost:9093
      negotiationType: plaintext
    mission:
      address: static://localhost:9094
      negotiationType: plaintext
    ai:
      address: static://localhost:9095
      negotiationType: plaintext

jwt:
  secret: dummy_jwt_secret_key_which_is_very_long_for_hmac_sha256_algorithm_to_work_properly
  access-expiration-ms: 3600000
  refresh-expiration-ms: 1209600000

oauth:
  google:
    client-id: 1042509386777-kalf6au8md4ef7n91mi5mb7c1pfg528u.apps.googleusercontent.com
    client-secret: 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