syntax = "proto3";

package p5laris.character.v1;

option java_multiple_files = true;
option java_package = "com.p5laris.proto.character.v1";
option java_outer_classname = "CharacterProto";

service CharacterService {
  rpc PingPong(PingPongRequest) returns (PingPongResponse);
}

message PingPongRequest {
  string message = 1;
}

message PingPongResponse {
  HealthStatus health_status = 1;
  string message = 2;
}

enum HealthStatus {
  HEALTH_STATUS_UNSPECIFIED = 0;
  HEALTHY = 1;
  UNHEALTHY = 2;
  DEGRADED = 3;
}
