server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: notification

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: false
  validate-on-migrate: true

grpc:
  server:
    port: ${GRPC_SERVER_PORT}
    reflection-service-enabled: ${GRPC_REFLECTION_ENABLED:false}

  client:
    event-log:
      address: ${EVENT_LOG_GRPC_ADDRESS}
      negotiationType: plaintext

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [traceId=%X{traceId}] %logger{36} - %msg%n"

internal:
  grpc-auth:
    enabled: ${INTERNAL_GRPC_AUTH_ENABLED:true}
    token: ${INTERNAL_GRPC_AUTH_TOKEN}

firebase:
  credentials:
    base64: ${FIREBASE_CREDENTIALS_BASE64:}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  health:
    db:
      enabled: true
