TRUNCATE TABLE item_usage_histories, user_items, items RESTART IDENTITY CASCADE;

INSERT INTO items (name, description, item_type, price, effect, effect_type, image_url, active, character_type_id) VALUES
-- Dawn skin: 1 thumbnail + 18 equipped assets
('푸른 새벽 스킨', '푸른 새벽처럼 신비로운 분위기의 스킨입니다.', 'SKIN', 100, NULL, NULL, '/assets/skins/dawn/thumbnails/skin-dawn-thumbnail.png', TRUE, NULL),
('푸른 새벽 스킨 - 쪼리 happy', '새벽 스킨 쪼리 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/jjori/core/skin-dawn-jjori-happy.png', FALSE, 3),
('푸른 새벽 스킨 - 쪼리 idle', '새벽 스킨 쪼리 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/jjori/core/skin-dawn-jjori-idle.png', FALSE, 3),
('푸른 새벽 스킨 - 쪼리 sleepy', '새벽 스킨 쪼리 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/jjori/core/skin-dawn-jjori-sleepy.png', FALSE, 3),
('푸른 새벽 스킨 - 쪼리 hungry', '새벽 스킨 쪼리 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/jjori/status/skin-dawn-jjori-hungry.png', FALSE, 3),
('푸른 새벽 스킨 - 쪼리 lonely', '새벽 스킨 쪼리 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/jjori/status/skin-dawn-jjori-lonely.png', FALSE, 3),
('푸른 새벽 스킨 - 쪼리 low-energy', '새벽 스킨 쪼리 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/jjori/status/skin-dawn-jjori-low-energy.png', FALSE, 3),
('푸른 새벽 스킨 - 무무 happy', '새벽 스킨 무무 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/mumu/core/skin-dawn-mumu-happy.png', FALSE, 2),
('푸른 새벽 스킨 - 무무 idle', '새벽 스킨 무무 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/mumu/core/skin-dawn-mumu-idle.png', FALSE, 2),
('푸른 새벽 스킨 - 무무 sleepy', '새벽 스킨 무무 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/mumu/core/skin-dawn-mumu-sleepy.png', FALSE, 2),
('푸른 새벽 스킨 - 무무 hungry', '새벽 스킨 무무 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/mumu/status/skin-dawn-mumu-hungry.png', FALSE, 2),
('푸른 새벽 스킨 - 무무 lonely', '새벽 스킨 무무 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/mumu/status/skin-dawn-mumu-lonely.png', FALSE, 2),
('푸른 새벽 스킨 - 무무 low-energy', '새벽 스킨 무무 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/mumu/status/skin-dawn-mumu-low-energy.png', FALSE, 2),
('푸른 새벽 스킨 - 노바 happy', '새벽 스킨 노바 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/nova/core/skin-dawn-nova-happy.png', FALSE, 1),
('푸른 새벽 스킨 - 노바 idle', '새벽 스킨 노바 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/nova/core/skin-dawn-nova-idle.png', FALSE, 1),
('푸른 새벽 스킨 - 노바 sleepy', '새벽 스킨 노바 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/nova/core/skin-dawn-nova-sleepy.png', FALSE, 1),
('푸른 새벽 스킨 - 노바 hungry', '새벽 스킨 노바 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/nova/status/skin-dawn-nova-hungry.png', FALSE, 1),
('푸른 새벽 스킨 - 노바 lonely', '새벽 스킨 노바 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/nova/status/skin-dawn-nova-lonely.png', FALSE, 1),
('푸른 새벽 스킨 - 노바 low-energy', '새벽 스킨 노바 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/dawn/equipped/nova/status/skin-dawn-nova-low-energy.png', FALSE, 1),

-- Night-sky skin: 1 thumbnail + 18 equipped assets
('은하수 오로라 스킨', '고요한 밤하늘처럼 깊고 차분한 분위기의 스킨입니다.', 'SKIN', 100, NULL, NULL, '/assets/skins/night-sky/thumbnails/skin-night-sky-thumbnail.png', TRUE, NULL),
('은하수 오로라 스킨 - 쪼리 happy', '밤하늘 스킨 쪼리 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/jjori/core/skin-night-sky-jjori-happy.png', FALSE, 3),
('은하수 오로라 스킨 - 쪼리 idle', '밤하늘 스킨 쪼리 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/jjori/core/skin-night-sky-jjori-idle.png', FALSE, 3),
('은하수 오로라 스킨 - 쪼리 sleepy', '밤하늘 스킨 쪼리 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/jjori/core/skin-night-sky-jjori-sleepy.png', FALSE, 3),
('은하수 오로라 스킨 - 쪼리 hungry', '밤하늘 스킨 쪼리 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/jjori/status/skin-night-sky-jjori-hungry.png', FALSE, 3),
('은하수 오로라 스킨 - 쪼리 lonely', '밤하늘 스킨 쪼리 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/jjori/status/skin-night-sky-jjori-lonely.png', FALSE, 3),
('은하수 오로라 스킨 - 쪼리 low-energy', '밤하늘 스킨 쪼리 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/jjori/status/skin-night-sky-jjori-low-energy.png', FALSE, 3),
('은하수 오로라 스킨 - 무무 happy', '밤하늘 스킨 무무 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/mumu/core/skin-night-sky-mumu-happy.png', FALSE, 2),
('은하수 오로라 스킨 - 무무 idle', '밤하늘 스킨 무무 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/mumu/core/skin-night-sky-mumu-idle.png', FALSE, 2),
('은하수 오로라 스킨 - 무무 sleepy', '밤하늘 스킨 무무 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/mumu/core/skin-night-sky-mumu-sleepy.png', FALSE, 2),
('은하수 오로라 스킨 - 무무 hungry', '밤하늘 스킨 무무 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/mumu/status/skin-night-sky-mumu-hungry.png', FALSE, 2),
('은하수 오로라 스킨 - 무무 lonely', '밤하늘 스킨 무무 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/mumu/status/skin-night-sky-mumu-lonely.png', FALSE, 2),
('은하수 오로라 스킨 - 무무 low-energy', '밤하늘 스킨 무무 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/mumu/status/skin-night-sky-mumu-low-energy.png', FALSE, 2),
('은하수 오로라 스킨 - 노바 happy', '밤하늘 스킨 노바 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/nova/core/skin-night-sky-nova-happy.png', FALSE, 1),
('은하수 오로라 스킨 - 노바 idle', '밤하늘 스킨 노바 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/nova/core/skin-night-sky-nova-idle.png', FALSE, 1),
('은하수 오로라 스킨 - 노바 sleepy', '밤하늘 스킨 노바 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/nova/core/skin-night-sky-nova-sleepy.png', FALSE, 1),
('은하수 오로라 스킨 - 노바 hungry', '밤하늘 스킨 노바 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/nova/status/skin-night-sky-nova-hungry.png', FALSE, 1),
('은하수 오로라 스킨 - 노바 lonely', '밤하늘 스킨 노바 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/nova/status/skin-night-sky-nova-lonely.png', FALSE, 1),
('은하수 오로라 스킨 - 노바 low-energy', '밤하늘 스킨 노바 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/night-sky/equipped/nova/status/skin-night-sky-nova-low-energy.png', FALSE, 1),

-- Starlight skin: 1 thumbnail + 18 equipped assets
('말랑 별빛 스킨', '말랑말랑하게 빛나는 별빛 분위기의 스킨입니다.', 'SKIN', 60, NULL, NULL, '/assets/skins/starlight/thumbnails/skin-starlight-thumbnail.png', TRUE, NULL),
('말랑 별빛 스킨 - 쪼리 happy', '별빛 스킨 쪼리 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/jjori/core/skin-starlight-jjori-happy.png', FALSE, 3),
('말랑 별빛 스킨 - 쪼리 idle', '별빛 스킨 쪼리 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/jjori/core/skin-starlight-jjori-idle.png', FALSE, 3),
('말랑 별빛 스킨 - 쪼리 sleepy', '별빛 스킨 쪼리 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/jjori/core/skin-starlight-jjori-sleepy.png', FALSE, 3),
('말랑 별빛 스킨 - 쪼리 hungry', '별빛 스킨 쪼리 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/jjori/status/skin-starlight-jjori-hungry.png', FALSE, 3),
('말랑 별빛 스킨 - 쪼리 lonely', '별빛 스킨 쪼리 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/jjori/status/skin-starlight-jjori-lonely.png', FALSE, 3),
('말랑 별빛 스킨 - 쪼리 low-energy', '별빛 스킨 쪼리 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/jjori/status/skin-starlight-jjori-low-energy.png', FALSE, 3),
('말랑 별빛 스킨 - 무무 happy', '별빛 스킨 무무 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/mumu/core/skin-starlight-mumu-happy.png', FALSE, 2),
('말랑 별빛 스킨 - 무무 idle', '별빛 스킨 무무 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/mumu/core/skin-starlight-mumu-idle.png', FALSE, 2),
('말랑 별빛 스킨 - 무무 sleepy', '별빛 스킨 무무 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/mumu/core/skin-starlight-mumu-sleepy.png', FALSE, 2),
('말랑 별빛 스킨 - 무무 hungry', '별빛 스킨 무무 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/mumu/status/skin-starlight-mumu-hungry.png', FALSE, 2),
('말랑 별빛 스킨 - 무무 lonely', '별빛 스킨 무무 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/mumu/status/skin-starlight-mumu-lonely.png', FALSE, 2),
('말랑 별빛 스킨 - 무무 low-energy', '별빛 스킨 무무 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/mumu/status/skin-starlight-mumu-low-energy.png', FALSE, 2),
('말랑 별빛 스킨 - 노바 happy', '별빛 스킨 노바 happy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/nova/core/skin-starlight-nova-happy.png', FALSE, 1),
('말랑 별빛 스킨 - 노바 idle', '별빛 스킨 노바 idle 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/nova/core/skin-starlight-nova-idle.png', FALSE, 1),
('말랑 별빛 스킨 - 노바 sleepy', '별빛 스킨 노바 sleepy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/nova/core/skin-starlight-nova-sleepy.png', FALSE, 1),
('말랑 별빛 스킨 - 노바 hungry', '별빛 스킨 노바 hungry 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/nova/status/skin-starlight-nova-hungry.png', FALSE, 1),
('말랑 별빛 스킨 - 노바 lonely', '별빛 스킨 노바 lonely 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/nova/status/skin-starlight-nova-lonely.png', FALSE, 1),
('말랑 별빛 스킨 - 노바 low-energy', '별빛 스킨 노바 low-energy 이미지입니다.', 'SKIN', 0, NULL, NULL, '/assets/skins/starlight/equipped/nova/status/skin-starlight-nova-low-energy.png', FALSE, 1),

-- Consumables
('별사탕밥', '캐릭터의 배고픔을 채워주는 달콤한 별사탕밥입니다.', 'CONSUMABLE', 10, 30, 'FOOD', '/assets/items/consumables/item-star-candy-meal.png', TRUE, NULL),
('구름 베개', '캐릭터의 피로를 풀어주는 푹신한 구름 베개입니다.', 'CONSUMABLE', 15, 40, 'REST', '/assets/items/consumables/item-cloud-pillow.png', TRUE, NULL),
('별 장난감', '캐릭터의 애정을 올려주는 귀여운 별 장난감입니다.', 'CONSUMABLE', 15, 40, 'PLAY', '/assets/items/consumables/item-star-toy.png', TRUE, NULL);
