CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 알림 ID

    user_id BIGINT NOT NULL, -- 수신 사용자 ID
    character_id BIGINT NULL, -- 말한 캐릭터 ID. SYSTEM 알림 등은 null 가능

    notification_type VARCHAR(30) NOT NULL, -- MISSION / CARE / ACHIEVEMENT / ATTENDANCE / SHARE / SYSTEM

    title VARCHAR(100) NOT NULL, -- 알림 제목
    message TEXT NOT NULL, -- 알림 내용

    target_type VARCHAR(30) NULL, -- 클릭 시 이동 대상 타입. MISSION / CHARACTER / ITEM / ACHIEVEMENT / SHARE
    target_id BIGINT NULL, -- 클릭 시 이동 대상 ID

    is_read BOOLEAN NOT NULL DEFAULT FALSE, -- 읽음 여부
    read_at TIMESTAMP NULL, -- 읽은 시각

    push_required BOOLEAN NOT NULL DEFAULT FALSE, -- FCM 푸시 발송 대상 여부

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 생성일
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- 수정일
);

CREATE TABLE fcm_device_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- FCM 토큰 ID

    user_id BIGINT NOT NULL, -- 사용자 ID

    fcm_token TEXT NOT NULL, -- FCM registration token 원문
    token_hash VARCHAR(64) NOT NULL, -- FCM token SHA-256 해시값

    platform VARCHAR(20) NOT NULL DEFAULT 'WEB', -- WEB / ANDROID / IOS

    active BOOLEAN NOT NULL DEFAULT TRUE, -- 활성 여부

    token_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 토큰 갱신 시각

    deactivated_at TIMESTAMP NULL, -- 비활성화 시각
    deactivated_reason VARCHAR(30) NULL, -- LOGOUT / PERMISSION_DENIED / TOKEN_INVALID / USER_DISABLED / STALE / UNKNOWN

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 생성일
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 수정일

    CONSTRAINT uk_fcm_device_tokens_token_hash
        UNIQUE (token_hash)
);

CREATE TABLE notification_push_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 푸시 발송 이력 ID

    notification_id BIGINT NOT NULL, -- 알림 ID
    user_id BIGINT NOT NULL, -- 수신 사용자 ID

    fcm_device_token_id BIGINT NULL, -- 발송 대상 FCM 토큰 ID. 토큰 조회 실패나 SKIPPED 이력은 null 가능

    delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING / SENT / FAILED / SKIPPED

    fcm_message_id VARCHAR(255) NULL, -- FCM 발송 성공 시 반환되는 message id

    error_code VARCHAR(100) NULL, -- FCM 실패 코드
    error_message TEXT NULL, -- FCM 실패 상세 메시지

    attempted_at TIMESTAMP NULL, -- 발송 시도 시각
    sent_at TIMESTAMP NULL, -- 발송 성공 시각
    failed_at TIMESTAMP NULL, -- 발송 실패 시각

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 생성일
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- 수정일
);

CREATE TABLE notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 필수, 알림 설정 ID

    user_id BIGINT NOT NULL, -- 사용자 ID

    push_enabled BOOLEAN NOT NULL DEFAULT TRUE, -- 전체 푸시 알림 허용 여부

    daily_push_limit INT NOT NULL DEFAULT 3, -- 하루 푸시 최대 발송 수

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 생성일
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- 수정일
);