apiVersion: 1

datasources:
  - name: PostgreSQL (Event Log)
    type: postgres
    access: proxy
    url: postgres-compose:5432
    user: root
    database: event_log
    secureJsonData:
      password: "12345678"
    jsonData:
      database: event_log
      sslmode: disable
      postgresVersion: 16
    isDefault: true
    editable: true

  - name: PostgreSQL (Users)
    type: postgres
    access: proxy
    url: postgres-compose:5432
    user: root
    database: users
    secureJsonData:
      password: "12345678"
    jsonData:
      database: users
      sslmode: disable
      postgresVersion: 16
    editable: true

  - name: PostgreSQL (AI)
    type: postgres
    access: proxy
    url: postgres-compose:5432
    user: root
    database: ai
    secureJsonData:
      password: "12345678"
    jsonData:
      database: ai
      sslmode: disable
      postgresVersion: 16
    editable: true

  - name: PostgreSQL (Monolith)
    type: postgres
    access: proxy
    url: postgres-compose:5432
    user: root
    database: monolith
    secureJsonData:
      password: "12345678"
    jsonData:
      database: monolith
      sslmode: disable
      postgresVersion: 16
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-compose:9090
    isDefault: false
    editable: true
