spring:
  application:
    name: character

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/character}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

grpc:
  server:
    port: 9092
    reflection-service-enabled: true

  client:
    user:
      address: static://localhost:9091
      negotiationType: plaintext
    item:
      address: static://localhost:9093
      negotiationType: plaintext
    mission:
      address: static://localhost:9094
      negotiationType: plaintext
    ai:
      address: static://localhost:9095
      negotiationType: plaintext